services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ganyan
      POSTGRES_USER: ganyan
      POSTGRES_PASSWORD: ganyan
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
