"""initial schema

Revision ID: 0c6e46ca4eb5
Revises: 
Create Date: 2026-04-05 01:16:46.110555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6e46ca4eb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('trainer', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scrape_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('track', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', name='scrapestatus'), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('surface_types', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('race_number', sa.SmallInteger(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('surface', sa.String(length=50), nullable=True),
    sa.Column('race_type', sa.String(length=100), nullable=True),
    sa.Column('horse_type', sa.String(length=100), nullable=True),
    sa.Column('weight_rule', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'resulted', 'cancelled', name='racestatus'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'date', 'race_number', name='uq_race_track_date_num')
    )
    op.create_index('ix_races_date', 'races', ['date'], unique=False)
    op.create_index('ix_races_track_date', 'races', ['track_id', 'date'], unique=False)
    op.create_table('race_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('horse_id', sa.Integer(), nullable=False),
    sa.Column('gate_number', sa.SmallInteger(), nullable=True),
    sa.Column('jockey', sa.String(length=200), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('hp', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('kgs', sa.SmallInteger(), nullable=True),
    sa.Column('s20', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('eid', sa.String(length=20), nullable=True),
    sa.Column('gny', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('agf', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_six', sa.String(length=50), nullable=True),
    sa.Column('finish_position', sa.SmallInteger(), nullable=True),
    sa.Column('finish_time', sa.String(length=20), nullable=True),
    sa.Column('performance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('predicted_probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_race_entries_horse_id', 'race_entries', ['horse_id'], unique=False)
    op.create_index('ix_race_entries_race_id', 'race_entries', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_race_entries_race_id', table_name='race_entries')
    op.drop_index('ix_race_entries_horse_id', table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_index('ix_races_track_date', table_name='races')
    op.drop_index('ix_races_date', table_name='races')
    op.drop_table('races')
    op.drop_table('tracks')
    op.drop_table('scrape_log')
    op.drop_table('horses')
    # ### end Alembic commands ###
